import { Song } from '@/types'

export const internationalBops: Song[] = [
  {
    id: "1",
    title: "Despacito (Remix) (feat. Justin Bieber)",
    artist: "Luis Fonsi & Daddy Yankee",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753871166/echo/songs/despacito.mp3",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870843/echo/images/Despacito%20%28Remix%29.jpg",
  },
  {
    id: "2",
    title: "Starboy (feat. Daft Punk)",
    artist: "The Weeknd",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753872564/echo/songs/starboy.mp3",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870885/echo/images/Starboy.jpg",
  },
  {
    id: "3",
    title: "Old Town Road (Remix) (feat. Billy Ray Cyrus)",
    artist: "Lil Nas X",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753872146/echo/songs/Oldtownroad.mp4",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870871/echo/images/Old%20town%20road.jpg",
  },
  {
    id: "4",
    title: "Shape of You",
    artist: "Ed Sheeran",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753872471/echo/songs/shapeofyou.mp3",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870883/echo/images/Shape%20of%20you.jpg",
  },
  {
    id: "5",
    title: "Industry Baby (feat. Jack Harlow)",
    artist: "Lil Nas X",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753871401/echo/songs/industrybaby.mp3",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870857/echo/images/Industry%20baby.jpg",
  },
  {
    id: "6",
    title: "Night Changes",
    artist: "One Direction",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753872037/echo/songs/NightChanges.mp4",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870868/echo/images/Night%20Changes.jpg",
  },
  {
    id: "7",
    title: "Señorita",
    artist: "Shawn Mendes & Camila Cabello",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753872442/echo/songs/senorita.mp3",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870881/echo/images/Senorita.jpg",
  },
  {
    id: "8",
    title: "Levitating",
    artist: "Dua Lipa",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753871761/echo/songs/levitating.mp3",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870863/echo/images/Levitating.jpg",
  },
  {
    id: "9",
    title: "Attention",
    artist: "Charlie Puth",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753870888/echo/songs/attention.mp3",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870830/echo/images/Attention.jpg",
  },
  {
    id: "10",
    title: "The Box",
    artist: "Roddy Ricch",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753872933/echo/songs/thebox.mp3",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870901/echo/images/The%20Box.jpg",
  },
  {
    id: "11",
    title: "Harleys in Hawaii",
    artist: "Katy Perry",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753871246/echo/songs/harleysinhawaii.mp3",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870850/echo/images/harleys%20in%20hawaii.jpg",
  },
  {
    id: "12",
    title: "Peaches (feat. Daniel Caesar & Giveon)",
    artist: "Justin Bieber",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753872179/echo/songs/peaches.mp3",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870873/echo/images/Peaches.jpg",
  },
  {
    id: "13",
    title: "Let Me Love You (feat. Justin Bieber)",
    artist: "DJ Snake",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753871729/echo/songs/LetMeLoveYou.mp4",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870862/echo/images/let%20me%20love%20you.jpg",
  },
  {
    id: "14",
    title: "The Hills",
    artist: "The Weeknd",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753872973/echo/songs/TheHills.mp4",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870904/echo/images/the%20hills.jpg",
  },
  {
    id: "15",
    title: "God's Plan",
    artist: "Drake",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753871221/echo/songs/GodsPlan.mp4",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870847/echo/images/God%27s%20plan.jpg",
  },
  {
    id: "16",
    title: "Timeless",
    artist: "The Weeknd",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753873075/echo/songs/Timeless.mp4",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870906/echo/images/Timeless.jpg",
  },
  {
    id: "17",
    title: "West Coast",
    artist: "Lana Del Rey",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753873398/echo/songs/WestCoast.mp4",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870919/echo/images/West%20Coast.jpg",
  },
  {
    id: "18",
    title: "Stereo Hearts (feat. Adam Levine)",
    artist: "Gym Class Heroes",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753872602/echo/songs/StereoHearts.mp4",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870886/echo/images/stereo%20hearts.jpg",
  },
  {
    id: "19",
    title: "All the Stars",
    artist: "Kendrick Lamar & SZA",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753870870/echo/songs/AlltheStars.mp4",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870829/echo/images/all%20the%20stars.jpg",
  },
  {
    id: "20",
    title: "POPSTAR (feat. Drake)",
    artist: "DJ Khaled",
    src: "https://res.cloudinary.com/ddkf3mink/video/upload/v1753872291/echo/songs/popstar.mp4",
    thumbnail: "https://res.cloudinary.com/ddkf3mink/image/upload/v1753870877/echo/images/popstar.jpg",
  },
]

export const bestOfBollywood: Song[] = [
  {
    id: '21',
    title: 'Ullu Ka Pattha (From "Jagga Jasoos")',
    artist: 'Arijit Singh & Nikhita Gandhi',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753873275/echo/songs/UllukaPattha.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870913/echo/images/Ullu%20ka%20pattha.jpg',
  },
  {
    id: '22',
    title: 'Bandook Meri Laila (From "A Gentleman") (feat. Sidharth Malhotra & Raftaar)',
    artist: 'Ash King & Jigar Saraiya',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753870966/echo/songs/BandookMeriLaila.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870835/echo/images/Bandook%20Meri%20Laila.jpg',
  },
  {
    id: '23',
    title: 'Binte Dil (From "Padmaavat")',
    artist: 'Arijit Singh',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753870986/echo/songs/BinteDil.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870836/echo/images/BinteDil.jpg',
  },
  {
    id: '24',
    title: 'Tu Chahiye (From "Bajrangi Bhaijaan")',
    artist: 'ATIF ASLAM, PRITAM & AMITABH BHATTACHARYA',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753873169/echo/songs/TuChahiye.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870909/echo/images/Tu%20Chahiye.jpg',
  },
  {
    id: '25',
    title: 'Saiyaara (Movie: Saiyaara)',
    artist: 'Faheem Abdullah, Arslan Nizami & Irshad Kamil',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753872403/echo/songs/Saiyaara.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870880/echo/images/saiyaara.jpg',
  },
  {
    id: '26',
    title: 'PHIR KABHI (REPRISE)',
    artist: 'ARIJIT SINGH & AMAAL MALLIK',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753872242/echo/songs/PhirKabhi.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870877/echo/images/Phir%20Kabhi.jpg',
  },
  {
    id: '27',
    title: 'Haan Main Galat (From "Love Aaj Kal")',
    artist: 'Pritam, Arijit Singh & Shashwat Singh',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753871239/echo/songs/HaanMainGalat.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870848/echo/images/Ha%20main%20galat.jpg',
  },
  {
    id: '28',
    title: 'Tu Meri',
    artist: 'Vishal Dadlani',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753873248/echo/songs/TuMeri.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870911/echo/images/Tu%20Meri.jpg',
  },
  {
    id: '29',
    title: 'Channa Mereya (From "Ae Dil Hai Mushkil")',
    artist: 'Arijit Singh',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753871120/echo/songs/ChannaMereya.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870841/echo/images/Channa%20mereya.jpg',
  },
  {
    id: '30',
    title: 'Kaise Hua (From "Kabir Singh")',
    artist: 'Vishal Mishra',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753871605/echo/songs/KaiseHua.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870859/echo/images/Kaise%20hua.jpg',
  },
  {
    id: '31',
    title: 'Zaalima',
    artist: 'Arijit Singh & Harshdeep Kaur',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753873537/echo/songs/Zaalima.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870933/echo/images/zaalima.jpg',
  },
  {
    id: '32',
    title: 'KABIRA (ENCORE)',
    artist: 'HARSHDEEP, ARIJIT SINGH, PRITAM & AMITABH BHATTACHARYA',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753871444/echo/songs/KABIRA.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870858/echo/images/kabira.jpg',
  },
  {
    id: '33',
    title: 'Main Agar (From "Tubelight")',
    artist: 'Pritam & Atif Aslam',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753871847/echo/songs/MainAgar.mp3',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870864/echo/images/main%20agar.jpg',
  },
  {
    id: '34',
    title: 'BADTAMEEZ DIL',
    artist: 'BENNY DAYAL, SHEFALI ALVARES, PRITAM & AMITABH BHATTACHARYA',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753870939/echo/songs/BadtameezDil.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870858/echo/images/kabira.jpg',
  },
  {
    id: '35',
    title: 'Shayad (From "Love Aaj Kal")',
    artist: 'Arijit Singh, Pritam',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753872534/echo/songs/Shayad.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870884/echo/images/shayad.jpg',
  },
  {
    id: '36',
    title: 'Chammak Challo',
    artist: 'Akon & Hamsika Iyer',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753871058/echo/songs/ChammakChallo.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870839/echo/images/chammak%20challo.jpg',
  },
  {
    id: '37',
    title: 'TU HAI KI NAHI',
    artist: 'ANKIT TIWARI & ABHENDRA KUMAR UPADHYAY',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753873217/echo/songs/TuHaiKeNahi.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870910/echo/images/tu%20hai%20ke%20nahi.jpg',
  },
  {
    id: '38',
    title: 'Hua Main',
    artist: 'Raghav Chaitanya & Pritam',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753871367/echo/songs/HuaMain.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870854/echo/images/hua%20main.jpg',
  },
  {
    id: '39',
    title: 'Tera Yaar Hoon Main',
    artist: 'Arijit Singh',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753872902/echo/songs/TeraYaarHoonMein.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870893/echo/images/tera%20yaar%20hoon%20main.jpg',
  },
  {
    id: '40',
    title: 'Kesariya (From "Brahmastra")',
    artist: 'Arijit Singh',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753871645/echo/songs/Kesariya.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870860/echo/images/kesariya.jpg',
  },
]



export const punjabiBangers: Song[] = [
  {
    id: '41',
    title: 'YEAH NAAH',
    artist: 'Karan Aujla & Ikky',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753873464/echo/songs/YeahNaah.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870928/echo/images/yeah%20naah.jpg',
  },
  {
    id: '42',
    title: 'These Days (feat. Bohemia)',
    artist: 'Sidhu Moose Wala',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753872999/echo/songs/TheseDays.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870905/echo/images/these%20days.jpg',
  },
  {
    id: '43',
    title: 'Teesri Manzil',
    artist: 'DIVINE',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753872782/echo/songs/TeesriManzil.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870888/echo/images/teesri%20manzil.jpg',
  },
  {
    id: '44',
    title: 'BAAWE',
    artist: 'Raftaar, Badshah and HITEN',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753870910/echo/songs/BAAWE.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870833/echo/images/baawe.jpg',
  },
  {
    id: '45',
    title: 'Dhundhala',
    artist: 'Yashraj, Dropped Out & Talwiinder',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753871195/echo/songs/Dhundhala.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870845/echo/images/dhundhala.jpg',
  },
  {
    id: '46',
    title: 'Russian Bandana',
    artist: 'Dhanda Nyoliwala',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753872348/echo/songs/RussianBandana.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870878/echo/images/russian%20bandana.jpg',
  },
  {
    id: '47',
    title: 'Desi Kalakaar',
    artist: 'Yo Yo Honey Singh',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753871145/echo/songs/DesiKalakar.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870842/echo/images/desi%20kalakar.jpg',
  },
  {
    id: '48',
    title: 'Supreme',
    artist: 'Shubh',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753872743/echo/songs/Supreme.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870887/echo/images/supreme.jpg',
  },
  {
    id: '49',
    title: 'Na Na Na Na',
    artist: 'J Star',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753871923/echo/songs/NANANANA.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870866/echo/images/nananana.jpg',
  },
  {
    id: '50',
    title: 'Born to Shine',
    artist: 'DILJIT DOSANJH',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753871032/echo/songs/BornToShine.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870838/echo/images/born%20to%20shine.jpg',
  },
  {
    id: '51',
    title: 'Tell Me',
    artist: 'Karan Aujla, OneRepublic & Ikky',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753872861/echo/songs/TellMe.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870890/echo/images/tell%20me.jpg',
  },
  {
    id: '52',
    title: 'Fell For You',
    artist: 'Shubh',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753871207/echo/songs/FellForYou.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870846/echo/images/fell%20for%20you.jpg',
  },
  {
    id: '53',
    title: '3:59 AM',
    artist: 'DIVINE',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753873032/echo/songs/threefivenine.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870897/echo/images/tfn.jpg',
  },
  {
    id: '54',
    title: 'Winning Speech',
    artist: 'Karan Aujla & Mxrci',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753873430/echo/songs/WinningSpeech.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870923/echo/images/winning%20speech.jpg',
  },
  {
    id: '55',
    title: 'Wavy',
    artist: 'Karan Aujla and Jay Trak',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753873305/echo/songs/Wavy.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870916/echo/images/wavy.jpg',
  },
  {
    id: '56',
    title: 'Love Dose',
    artist: 'Yo Yo Honey Singh',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753871821/echo/songs/LoveDose.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870842/echo/images/desi%20kalakar.jpg',
  },
  {
    id: '57',
    title: 'Top Class / Overseas',
    artist: 'DIVINE & Karan Aujla',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753873114/echo/songs/TopClass.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870908/echo/images/top%20class.jpg',
  },
  {
    id: '58',
    title: 'No Cap',
    artist: 'KR$NA',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753872102/echo/songs/NoCap.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870870/echo/images/no%20cap.jpg',
  },
  {
    id: '59',
    title: 'Nanchaku',
    artist: 'Seedhe Maut & MC STAN',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753871985/echo/songs/Nanchaku.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870867/echo/images/nanchaku.jpg',
  },
  {
    id: '60',
    title: 'High Rated Gabru',
    artist: 'Guru Randhawa',
    src: 'https://res.cloudinary.com/ddkf3mink/video/upload/v1753871291/echo/songs/HighRatedGabru.mp4',
    thumbnail: 'https://res.cloudinary.com/ddkf3mink/image/upload/v1753870852/echo/images/high%20rated%20ghabru.jpg',
  },
]



// 🔁 Merge all songs for Listen Again etc.
export const allSongs: Song[] = [
  ...internationalBops,
  ...bestOfBollywood,
  ...punjabiBangers
]